# galaxy_build_client: false
galaxy_commit_id: release_24.2

csnt_brand: QA2-TEST

pulsar:
  user_name: galaxy-qa1
  nfs_home: brno11-elixir
  nfs_prefix: pulsar-qa2
  pbs_queue: galaxyqa
  pbs_gpu_queue: galaxy_gpu
pulsar_data_dir: "/storage/{{ pulsar.nfs_home }}/home/{{ pulsar.user_name }}/{{ pulsar.nfs_prefix }}"
