#! vim: ts=2 expandtab:

name: test-tools-playbook

runs:
  using: 'composite'
  steps:
    - name: Create vault password
      shell: bash
      run: echo "$VAULT_PASSWORD" >.vault-password.txt

    - name: Run galaxy_tests.yaml playbook
      shell: bash
      run: ansible-playbook -vvv --limit $TARGET_HOSTNAME galaxy_tests.yml

    - name: Upload test report to display
      uses: actions/upload-artifact@v4
      with:
        name: test-tool-report
        path: test_tools_report.html
        if-no-files-found: error
