#! vim: ts=2 expandtab:

name: test-tools-playbook

runs:
  using: 'composite'
  steps:
    - name: Make SSH connection
      shell: bash
      run: |
        mkdir -p $HOME/.ssh
        install -m 600 -D /dev/null $HOME/.ssh/id_rsa
        echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
        ssh -f -o StrictHostKeyChecking=no $TARGET_USER@$TARGET_HOSTNAME hostname

    - name: Create vault password
      shell: bash
      run: echo "$VAULT_PASSWORD" >.vault-password.txt

    - name: Run galaxy_tests.yaml playbook
      shell: bash
      run: ansible-playbook -vvv --limit $TARGET_HOSTNAME galaxy_tests.yml

    - name: Upload test report to display
      uses: actions/upload-artifact@v4
      with:
        name: test-tool-report
        path: test_tools_report.html
        if-no-files-found: error
