---
- hosts: galaxyservers
  tasks:
    - name: Ensure virtualenv is present
      local_action:
        module: ansible.builtin.pip
        name: virtualenv

    - name: Create a Python virtual environment for Ephemeris
      local_action:
        module: ansible.builtin.command
        cmd: python3 -m venv /tmp/ephemeris

    - name: Install Ephemeris
      local_action:
        module: ansible.builtin.pip
        name: 
        - ephemeris
        - setuptools
        virtualenv: /tmp/ephemeris

    - name: Copy tools from master instance
      local_action:
        module: ansible.builtin.shell
        cmd: /tmp/ephemeris/bin/get-tool-list -g https://{{ copy_tools_from }} -o /tmp/master_tool_list.yaml
      when: copy_tools_from

    - name: Install tools from master instance
      local_action:
        module: ansible.builtin.shell
        cmd: /tmp/ephemeris/bin/shed-tools install -g https://{{ inventory_hostname }} -a {{ api_key }} -t /tmp/master_tool_list.yaml
      when: copy_tools_from

    - name: Install instance specific tools
      local_action:
        module: ansible.builtin.shell
        cmd: /tmp/ephemeris/bin/shed-tools install -g https://{{ inventory_hostname }} -a {{ api_key }} -t files/{{ inventory_hostname }}/tool_list.yaml
