galaxyservers:
  hosts:
    galaxy-gxit.grid.cesnet.cz:
      ansible_user: debian
    galaxy-umsa.grid.cesnet.cz:
      ansible_user: galaxy
    usegalaxy-test.cerit-sc.cz:
      ansible_user: debian
    usegalaxy.cz:
      ansible_user: galaxy-cz
    galaxy-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    galaxy-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian
# higher variable precedence
  children:
    noletsencrypt:

dbservers:
  children: galaxyservers

noletsencrypt:
  hosts:
    galaxy-gxit.grid.cesnet.cz:
