# define for all our hosts 
# expected to run ansible-playbook ... --limit HOSTNAME

galaxyservers:
  hosts:
    galaxy-gxit.grid.cesnet.cz:
      ansible_user: debian
    usegalaxy-test.cerit-sc.cz: 
      ansible_user: debian
    galaxy-qa1.galaxy.cloud.e-infra.cz:
      ansible_user: debian
    galaxy-qa2.galaxy.cloud.e-infra.cz:
      ansible_user: debian
# higher variable precedence 
  children:
    noletsencrypt:

dbservers:
  children: galaxyservers


noletsencrypt:
  hosts:
    galaxy-gxit.grid.cesnet.cz:
