# define for all our hosts 
# expected to run ansible-playbook ... --limit HOSTNAME

galaxyservers:
  hosts:
    galaxy-gxit.grid.cesnet.cz:
      ansible_user: debian
# higher variable precedence 
  children:
    noletsencrypt:

dbservers:
  children: galaxyservers


noletsencrypt:
  hosts:
    galaxy-gxit.grid.cesnet.cz:
