# where to put most of the data; we use RBD or NBD volumes
galaxy_mutable_data_dir: /rbd/galaxy-umsa_data
galaxy_mutable_config_dir: "{{ galaxy_root }}/var/config"
galaxy_gravity_state_dir: "{{ galaxy_root }}/var/gravity"
galaxy_tool_dependency_dir: "{{ galaxy_root }}/var/dependencies"

galaxy_commit_id: release_24.2
# galaxy_build_client: false

csnt_log_level: DEBUG
csnt_enable_notification_system: true
csnt_short_term_storage_dir: /rbd/data/short_term_web_storage
csnt_tool_config_file:
- "{{ galaxy_config_dir }}/tool_conf.xml"
- "{{ galaxy_config_dir }}/local_tool_conf.xml"
# csnt_edam_panel_views: operations,topics
# csnt_default_panel_view: all_tools
enable_tiaas: false

galaxy_user_name: galaxyumsa
galaxy_user_group: galaxyumsa

pulsar:
  user_name: galaxyumsa
  nfs_home: brno11-elixir
  nfs_prefix: pulsar-umsa
  pbs_queue: galaxyumsa
  pbs_gpu_queue: galaxy_gpu

pulsar_data_dir: "/storage/{{ pulsar.nfs_home }}/home/{{ pulsar.user_name }}/{{ pulsar.nfs_prefix }}"

galaxy_config_files:
  - src: files/galaxy/themes.yml
    dest: "{{ galaxy_config.galaxy.themes_config_file }}"
  - src: "files/{{ inventory_hostname }}/tpv_rules_local.yml"
    dest: "{{ tpv_mutable_dir }}/tpv_rules_{{ inventory_hostname }}.yml"
  - src: "{{ lookup('first_found', ['files/'+inventory_hostname+'/config/tool_conf.xml', 'files/galaxy/config/tool_conf.xml']) }}"
    dest: "{{ galaxy_config_dir }}/tool_conf.xml"
  - src: files/galaxy/config/oidc_config.xml
    dest: "{{ galaxy_config_dir }}/oidc_config.xml"
#  - src: "files/{{ inventory_hostname }}/tool_conf_labels.xml"
#    dest: "{{ galaxy_config_dir }}/tool_conf_labels.xml"
#  - src: "files/{{ inventory_hostname }}/all_tools.yml"
#    dest: "{{ galaxy_config_dir }}/plugins/activities/all_tools.yml"
