#! vim: ts=2 expandtab:

name: deploy-common

on: [ workflow_call ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install Ansible
        run: echo {{ destination }}
