#! vim: ts=2 expandtab:

name: deploy-common

runs:
  using: 'composite'
  steps:
    - name: Create SSH key
      shell: bash
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        cp known_hosts ~/.ssh/known_hosts
        ssh $USER@$HOSTNAME hostname -f

    - name: Install Ansible requirements
      shell: bash
      run: ansible-galaxy install -p roles -r requirements.yml

    - name: Vault password
      shell: bash
      run: echo "$VAULT_PASSWORD" >.vault-password.txt

    - name: Run playbook
      shell: bash
      run: ansible-playbook --limit $HOSTNAME galaxy.yml
