#! vim: ts=2 expandtab:

name: deploy-common


inputs:
  destination:
    description: 'Ansible host'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      use: actions/checkout@v2

    - name: Test Ansible
      shell: bash
      run: ansible-playbook --help


#    - 
#      run: echo ${{ inputs.destination }}
#      shell: bash
