global:
  default_inherits: default

tools:
  default:
    abstract: true
    cores: 1
    mem: cores * 4
    scheduling:
      require:
        - pulsar
  .*testing.*:
    cores: 2
    mem: cores * 4
    params:
      walltime: 8
    rules:
      - id: admin_only_testing_tool
        if: |
          # Only allow the tool to be executed if the user is an admin
          admin_users = app.config.admin_users
          # last line in block must evaluate to a value - which determines whether the TPV if conditional matches or not
          not user or user.email not in admin_users
        fail: Unauthorized. Only admins can execute this tool.

      - id: resource_params_defined
        if: |
          param_dict = job.get_param_values(app)
          param_dict.get('__job_resource', {}).get('__job_resource__select') == 'yes'
        cores: int(job.get_param_values(app)['__job_resource']['cores'])
        params:
           walltime: "{int(job.get_param_values(app)['__job_resource']['time'])}"
#  .*/bwa/.*:
#    scheduling:
#      require:
#        - pulsar
#  .*/bwa_mem/.*:
#    scheduling:
#      require:
#        - pulsar

destinations:
  local_env:
    runner: local_runner
    max_accepted_cores: 1
    params:
      tmp_dir: true
  singularity:
    runner: local_runner
    max_accepted_cores: 1
    params:
      singularity_enabled: true
    env:
      # Ensuring a consistent collation environment is good for reproducibility.
      LC_ALL: C
      # The cache directory holds the docker containers that get converted
      SINGULARITY_CACHEDIR: /tmp/singularity
      # Singularity uses a temporary directory to build the squashfs filesystem
      APPTAINER_TMPDIR: /tmp
  pulsar:
    runner: pulsar_runner
    max_accepted_cores: 128
    max_accepted_mem: 512
    max_accepted_gpus: 2
    max_cores: 16
    max_mem: 64
    max_gpus: 1
    params:
      default_file_action: remote_transfer
      dependency_resolution: remote
      jobs_directory: /storage/praha5-elixir/home/galaxyeu/pulsar-test/files/staging
      persistence_directory: /storage/praha5-elixir/home/galaxyeu/pulsar-test/files/persisted_data
      remote_metadata: false
      rewrite_parameters: true
      transport: curl
      outputs_to_working_directory: false
    scheduling:
      require:
        - pulsar
