galaxy_commit_id: release_24.1

csnt_brand: QA1-TEST
csnt_log_level: DEBUG

pulsar:
  user_name: galaxy-qa1
  nfs_home: brno11-elixir
  nfs_prefix: pulsar-qa1
  pbs_queue: galaxyqa
  pbs_gpu_queue: galaxy_gpu

pulsar_data_dir: "/storage/{{ pulsar.nfs_home }}/home/{{ pulsar.user_name }}/{{ pulsar.nfs_prefix }}"

galaxy_config_files:
  - src: files/galaxy/themes.yml
    dest: "{{ galaxy_config.galaxy.themes_config_file }}"
  - src: "files/{{ inventory_hostname }}/tpv_rules_local.yml"
    dest: "{{ tpv_mutable_dir }}/tpv_rules_{{ inventory_hostname }}.yml"
  - src: files/{{ inventory_hostname }}/file_sources_conf.yml
    dest: "{{ galaxy_config_dir }}/file_sources_conf.yml"
  - src: files/{{ inventory_hostname }}/user_preferences_extra_conf.yml
    dest: "{{ galaxy_config_dir }}/user_preferences_extra_conf.yml"
  - src: "{{ lookup('first_found', ['templates/'+inventory_hostname+'/config/tool_conf.xml.j2', 'files/galaxy/config/tool_conf.xml']) }}"
    dest: "{{ galaxy_config.galaxy.tool_config_file[0] }}"
  - src: files/galaxy/config/oidc_config.xml
    dest: "{{ galaxy_config_dir }}/oidc_config.xml"

# copy_tools_from: usegalaxy.eu

# just test
#extra_certbot_domains:
# - "nonexistent.domain"
