#! vim: ts=2 expandtab:

name: deploy-test

on: [ workflow_dispatch ]

jobs:
  call-common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call common
        uses: ./.github/actions/deploy-common
        with:
          destination: 'usegalaxy-test.cerit-sc.cz'
          user: 'debian'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD }}


