#! vim: ts=2 expandtab:

name: deploy-test

# TODO: run automatically on push to main
on: [ workflow_dispatch ]

jobs:
  call-common:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        destination:
        - test-cz:
          env:
            HOSTNAME: usegalaxy-test.cerit-sc.cz
            USER: debian
            VAULT_PASSWORD: ${{ secrets.VAULT_PASSWORD_TEST_CZ }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TEST_CZ }}
# TODO: other test hosts here
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Call common
        uses: ./.github/actions/deploy-common
