#! vim: ts=2 expandtab:

name: deploy-test

on: [ workflow_dispatch ]

jobs:
  call-common:
    runs-on: ubuntu-latest
    steps:
      - name: Call common
        uses: ./.github/actions/deploy-common
        with:
          destination: 'usegalaxy-test.blablabla'


