#! vim: ts=2 expandtab:

name: deploy-test

on: [ workflow_dispatch ]

jobs:
  call-common:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Call common
        uses: ./.github/workflows/deploy-common.yaml
        with:
          destination: 'usegalaxy-test.blablabla'


